# DeadHour - Analysis Options Configuration (2025 Best Practices)
# Modern Flutter analysis configuration following 2025 recommendations

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "trash/**"
    - "lib/generated/**"
    - "build/**"
    - "android/**"
    - "ios/**"
    - "web/**"
    - "windows/**"
    - "linux/**"
    - "macos/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

  errors:
    # Critical errors that must be addressed
    missing_return: error
    invalid_assignment: error
    argument_type_not_assignable: error
    undefined_method: error
    undefined_getter: error
    undefined_setter: error
    
    # Warnings for code quality
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
    deprecated_member_use: warning
    
    # Allow during development
    todo: info
    fixme: info

linter:
  rules:
    # === CRITICAL SAFETY RULES (2025) ===
    avoid_void_async: true
    always_declare_return_types: true
    avoid_catches_without_on_clauses: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    hash_and_equals: true
    no_duplicate_case_values: true
    test_types_in_equals: true
    throw_in_finally: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # === FLUTTER SPECIFIC (2025) ===
    use_build_context_synchronously: true
    avoid_web_libraries_in_flutter: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_colored_box: true
    use_decorated_box: true

    # === MODERN DART PRACTICES (2025) ===
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    prefer_single_quotes: true
    annotate_overrides: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_statements: true
    avoid_unused_constructor_parameters: true
    unnecessary_overrides: true
    avoid_redundant_argument_values: true
    avoid_return_types_on_setters: true
    prefer_collection_literals: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    use_super_parameters: true

    # === NULL SAFETY (2025) ===
    avoid_returning_null_for_void: true
    null_closures: true
    prefer_void_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null_for_future: true

    # === PERFORMANCE (2025) ===
    avoid_slow_async_io: true
    avoid_function_literals_in_foreach_calls: true
    control_flow_in_finally: true
    empty_catches: true
    no_adjacent_strings_in_list: true

    # === CODE STYLE (2025) ===
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: true
    library_names: true
    library_prefixes: true
    avoid_types_as_parameter_names: true

    # === RELAXED FOR DEVELOPMENT ===
    avoid_print: false  # Allow print statements for debugging
    public_member_api_docs: false  # Don't require docs during development
    lines_longer_than_80_chars: false  # Allow longer lines
    sort_constructors_first: false
    cascade_invocations: false
    constant_identifier_names: false
    diagnostic_describe_all_properties: false
