name: deadhour_flutter
description: DeadHour - World's first infinite-scalability ADDON platform for Morocco

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Internationalization
  intl: ^0.18.1
  
  # HTTP & Networking
  http: ^1.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Date & Time
  timezone: ^0.9.2
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Image Picker
  image_picker: ^1.0.4
  
  # URL Launcher
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

