import '../models/room.dart';

/// Mock room data for Morocco community chat rooms
class RoomData {
  static List<Room> get rooms => [
        Room(
          id: '1',
          name: '#coffee-afternoon-deals-casa',
          displayName: 'Coffee Afternoon Deals Casa',
          category: 'food',
          city: 'Casablanca',
          description:
              'Share weekend spa deals and wellness experiences in Casa',
          memberCount: 156,
          onlineCount: 23,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: true,
          createdAt: DateTime.now().subtract(const Duration(days: 45)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 2)),
          moderators: ['1', '3'],
          recentMessages: [
            {
              'id': 'm1',
              'userId': 'bot',
              'userName': 'DeadHour Bot',
              'message':
                  '🚨 FLASH DEAL! Café Atlas Maarif: 50% OFF ⏰ Next 2 hours only',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 2)),
              'type': 'deal_alert',
            },
            {
              'id': 'm2',
              'userId': '1',
              'userName': 'Ahmed_Casa',
              'message':
                  'Perfect timing! I was just looking for a good coffee spot near Twin Center 👍',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 1)),
              'type': 'message',
            },
            {
              'id': 'm3',
              'userId': '2',
              'userName': 'Sara_Local',
              'message':
                  '@Ahmed_Casa Atlas has amazing pastries too! Try the chebakia 🥮',
              'timestamp': DateTime.now().subtract(const Duration(seconds: 30)),
              'type': 'message',
            },
          ],
        ),
        Room(
          id: '2',
          name: '#escape-rooms-weekend',
          displayName: 'Escape Rooms Weekend',
          category: 'entertainment',
          city: 'Casablanca',
          description: 'Plan weekend escape room adventures and form teams',
          memberCount: 89,
          onlineCount: 12,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: false,
          createdAt: DateTime.now().subtract(const Duration(days: 32)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 5)),
          moderators: ['3'],
          recentMessages: [
            {
              'id': 'm4',
              'userId': '3',
              'userName': 'Omar_Casa',
              'message':
                  'Saturday team formation for Morocco Mall! Who\'s in? 🎮',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 5)),
              'type': 'message',
            },
            {
              'id': 'm5',
              'userId': '2',
              'userName': 'Sarah_Tourist_FR',
              'message': 'I\'d love to join! Is it beginner-friendly? 🇫🇷',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 3)),
              'type': 'message',
            },
          ],
        ),
        Room(
          id: '3',
          name: '#cultural-experiences-marrakech',
          displayName: 'Cultural Experiences Marrakech',
          category: 'tourism',
          city: 'Marrakech',
          description: 'Authentic Marrakech experiences with local guides',
          memberCount: 234,
          onlineCount: 45,
          isPublic: false,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: true,
          createdAt: DateTime.now().subtract(const Duration(days: 67)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 1)),
          moderators: ['3'],
          isPremiumOnly: true,
          recentMessages: [
            {
              'id': 'm6',
              'userId': '3',
              'userName': 'Local_Expert_Youssef',
              'message':
                  'Hassan II Mosque tour available now! 2 hours • 15€ • English/French 🕌',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 1)),
              'type': 'experience_offer',
            },
          ],
        ),
        Room(
          id: '4',
          name: '#padel-players-casa',
          displayName: 'Padel Players Casa',
          category: 'sports',
          city: 'Casablanca',
          description: 'Connect with padel players for matches and tournaments',
          memberCount: 178,
          onlineCount: 34,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: false,
          createdAt: DateTime.now().subtract(const Duration(days: 23)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 15)),
          moderators: ['2'],
          recentMessages: [
            {
              'id': 'm7',
              'userId': '2',
              'userName': 'Ahmed_Padel',
              'message':
                  'Looking for doubles partner tomorrow 6PM at Royal Club 🎾',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 15)),
              'type': 'match_request',
            },
          ],
        ),
        Room(
          id: '5',
          name: '#family-activities-rabat',
          displayName: 'Family Activities Rabat',
          category: 'family',
          city: 'Rabat',
          description:
              'Plan family-friendly activities and kids\' entertainment',
          memberCount: 245,
          onlineCount: 19,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: true,
          createdAt: DateTime.now().subtract(const Duration(days: 31)),
          lastActivity: DateTime.now().subtract(const Duration(hours: 2)),
          moderators: ['4'],
          recentMessages: [
            {
              'id': 'm8',
              'userId': '4',
              'userName': 'Fatima_Mom3',
              'message':
                  'Mega Mall indoor playground has 50% off weekdays! Perfect for toddlers 🎪',
              'timestamp': DateTime.now().subtract(const Duration(hours: 2)),
              'type': 'deal_share',
            },
          ],
        ),
        Room(
          id: '6',
          name: '#spa-deals-marrakech',
          displayName: 'Spa Deals Marrakech',
          category: 'wellness',
          city: 'Marrakech',
          description: 'Exclusive spa and hammam deals in Marrakech',
          memberCount: 312,
          onlineCount: 67,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: true,
          createdAt: DateTime.now().subtract(const Duration(days: 52)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 8)),
          moderators: ['1', '2'],
          recentMessages: [
            {
              'id': 'm9',
              'userId': '1',
              'userName': 'Aicha_Wellness',
              'message':
                  'La Mamounia Spa - afternoon slots 40% off today! Book before 2PM 💆‍♀️',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 8)),
              'type': 'urgent_deal',
            },
          ],
        ),
        Room(
          id: '7',
          name: '#street-food-fez',
          displayName: 'Street Food Fez',
          category: 'food',
          city: 'Fez',
          description:
              'Discover authentic street food and local eateries in Fez medina',
          memberCount: 189,
          onlineCount: 28,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: true,
          isHalalOnly: true,
          createdAt: DateTime.now().subtract(const Duration(days: 38)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 22)),
          moderators: ['3'],
          recentMessages: [
            {
              'id': 'm10',
              'userId': '3',
              'userName': 'Hassan_FoodGuide',
              'message':
                  'Best tajine in medina RIGHT NOW! Chez Ahmed - tourists pay 80DH, locals 45DH 🍲',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 22)),
              'type': 'local_tip',
            },
          ],
        ),
        Room(
          id: '8',
          name: '#gaming-night-tangier',
          displayName: 'Gaming Night Tangier',
          category: 'entertainment',
          city: 'Tangier',
          description: 'Board games, video games, and social gaming events',
          memberCount: 134,
          onlineCount: 41,
          isPublic: true,
          allowDeals: true,
          isPrayerTimeAware: false,
          isHalalOnly: false,
          createdAt: DateTime.now().subtract(const Duration(days: 19)),
          lastActivity: DateTime.now().subtract(const Duration(minutes: 4)),
          moderators: ['2', '4'],
          recentMessages: [
            {
              'id': 'm11',
              'userId': '2',
              'userName': 'Youssef_Gamer',
              'message':
                  'FIFA tournament tonight at Game Zone! Entry 30DH, winner takes 200DH 🎮',
              'timestamp': DateTime.now().subtract(const Duration(minutes: 4)),
              'type': 'event_announcement',
            },
          ],
        ),
      ];
}