import '../models/deal.dart';

/// Mock deal data for Morocco venues during dead hours
class DealData {
  static List<Deal> get deals => [
        Deal(
          id: '1',
          venueId: '1',
          title: 'Afternoon Coffee Special',
          description:
              'Perfect afternoon study spot! Quiet atmosphere, great coffee, free WiFi.',
          discountType: 'percentage',
          discountValue: 35,
          originalPrice: 65,
          discountedPrice: 42,
          validFrom: DateTime.now().subtract(const Duration(hours: 2)),
          validUntil: DateTime.now().add(const Duration(hours: 2)),
          maxCapacity: 20,
          currentBookings: 7,
          isActive: true,
          categories: ['coffee', 'study', 'wifi'],
          daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
          timeSlots: ['14:00-16:00'],
        ),
        Deal(
          id: '2',
          venueId: '2',
          title: 'Traditional Lunch Experience',
          description:
              'Authentic Moroccan tagine and couscous during lunch hours',
          discountType: 'percentage',
          discountValue: 25,
          originalPrice: 120,
          discountedPrice: 90,
          validFrom: DateTime.now().subtract(const Duration(hours: 1)),
          validUntil: DateTime.now().add(const Duration(hours: 3)),
          maxCapacity: 15,
          currentBookings: 8,
          isActive: true,
          categories: ['traditional', 'lunch', 'tagine'],
          daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
          timeSlots: ['14:00-16:00'],
        ),
        Deal(
          id: '3',
          venueId: '3',
          title: 'Weekday Escape Challenge',
          description:
              'Team building escape room experience during off-peak hours',
          discountType: 'percentage',
          discountValue: 40,
          originalPrice: 480,
          discountedPrice: 288,
          validFrom: DateTime.now().subtract(const Duration(minutes: 30)),
          validUntil: DateTime.now().add(const Duration(hours: 4)),
          maxCapacity: 6,
          currentBookings: 2,
          isActive: true,
          categories: ['team', 'challenge', 'group'],
          daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday'],
          timeSlots: ['14:00-17:00'],
        ),
        Deal(
          id: '4',
          venueId: '4',
          title: 'Relaxing Hammam Session',
          description:
              'Traditional Moroccan hammam experience with essential oils',
          discountType: 'percentage',
          discountValue: 30,
          originalPrice: 150,
          discountedPrice: 105,
          validFrom: DateTime.now().subtract(const Duration(hours: 1)),
          validUntil: DateTime.now().add(const Duration(hours: 5)),
          maxCapacity: 8,
          currentBookings: 3,
          isActive: true,
          categories: ['relaxation', 'traditional', 'wellness'],
          daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
          timeSlots: ['14:00-17:00'],
        ),
        Deal(
          id: '5',
          venueId: '5',
          title: 'Weekday Racing Special',
          description: 'Professional go-kart racing with timing system',
          discountType: 'percentage',
          discountValue: 45,
          originalPrice: 200,
          discountedPrice: 110,
          validFrom: DateTime.now(),
          validUntil: DateTime.now().add(const Duration(hours: 6)),
          maxCapacity: 12,
          currentBookings: 4,
          isActive: true,
          categories: ['racing', 'adrenaline', 'competition'],
          daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday'],
          timeSlots: ['14:00-18:00'],
        ),
      ];
}