import '../models/venue.dart';
import '../models/deal.dart';
import '../models/user.dart';
import '../models/room.dart';

class MockData {
  // Mock Venues
  static List<Venue> get venues => [
    Venue(
      id: '1',
      name: 'Café Central Gueliz',
      category: 'food',
      type: 'Mediterranean Café',
      address: '123 Rue Mohammed V, Gueliz, Casablanca',
      city: 'Casablanca',
      rating: 4.6,
      reviewCount: 234,
      imageUrl: 'https://picsum.photos/400/300?random=11',
      description: 'Authentic Mediterranean café with traditional Moroccan atmosphere',
      phone: '+212 522 123 456',
      operatingHours: {
        'monday': '08:00-23:00',
        'tuesday': '08:00-23:00',
        'wednesday': '08:00-23:00',
        'thursday': '08:00-23:00',
        'friday': '08:00-23:00',
        'saturday': '09:00-24:00',
        'sunday': '09:00-22:00',
      },
      isHalal: true,
      hasWifi: true,
      acceptsCards: true,
      priceRange: '€€',
      latitude: 33.5731,
      longitude: -7.5898,
    ),
    
    Venue(
      id: '2',
      name: 'Restaurant Al Fassia',
      category: 'food',
      type: 'Traditional Moroccan',
      address: '232 Avenue Mohammed V, Gueliz, Marrakech',
      city: 'Marrakech',
      rating: 4.8,
      reviewCount: 456,
      imageUrl: 'https://picsum.photos/400/300?random=12',
      description: 'Authentic Moroccan cuisine in traditional setting',
      phone: '+212 524 234 567',
      operatingHours: {
        'monday': '12:00-22:00',
        'tuesday': '12:00-22:00',
        'wednesday': '12:00-22:00',
        'thursday': '12:00-22:00',
        'friday': '12:00-23:00',
        'saturday': '12:00-23:00',
        'sunday': '12:00-22:00',
      },
      isHalal: true,
      hasWifi: false,
      acceptsCards: true,
      priceRange: '€€€',
      latitude: 31.6295,
      longitude: -7.9811,
    ),
    
    Venue(
      id: '3',
      name: 'Escape Hunt Morocco Mall',
      category: 'entertainment',
      type: 'Escape Room',
      address: 'Morocco Mall, Casablanca',
      city: 'Casablanca',
      rating: 4.5,
      reviewCount: 189,
      imageUrl: 'https://picsum.photos/400/300?random=13',
      description: 'Thrilling escape room experiences for groups',
      phone: '+212 522 345 678',
      operatingHours: {
        'monday': '10:00-22:00',
        'tuesday': '10:00-22:00',
        'wednesday': '10:00-22:00',
        'thursday': '10:00-22:00',
        'friday': '10:00-23:00',
        'saturday': '10:00-23:00',
        'sunday': '10:00-22:00',
      },
      isHalal: true,
      hasWifi: true,
      acceptsCards: true,
      priceRange: '€€',
      latitude: 33.5731,
      longitude: -7.6298,
    ),
    
    Venue(
      id: '4',
      name: 'Hammam de la Rose',
      category: 'wellness',
      type: 'Traditional Hammam',
      address: '45 Rue de la Liberté, Rabat',
      city: 'Rabat',
      rating: 4.7,
      reviewCount: 123,
      imageUrl: 'https://picsum.photos/400/300?random=14',
      description: 'Traditional Moroccan hammam experience',
      phone: '+212 537 456 789',
      operatingHours: {
        'monday': '09:00-20:00',
        'tuesday': '09:00-20:00',
        'wednesday': '09:00-20:00',
        'thursday': '09:00-20:00',
        'friday': '14:00-20:00',
        'saturday': '09:00-21:00',
        'sunday': '09:00-20:00',
      },
      isHalal: true,
      hasWifi: false,
      acceptsCards: false,
      priceRange: '€€',
      latitude: 34.0209,
      longitude: -6.8416,
    ),
    
    Venue(
      id: '5',
      name: 'Karting Club Casa',
      category: 'entertainment',
      type: 'Go-Kart Racing',
      address: 'Zone Industrielle Sidi Bernoussi, Casablanca',
      city: 'Casablanca',
      rating: 4.4,
      reviewCount: 267,
      imageUrl: 'https://picsum.photos/400/300?random=15',
      description: 'Professional go-kart racing track',
      phone: '+212 522 567 890',
      operatingHours: {
        'monday': '14:00-22:00',
        'tuesday': '14:00-22:00',
        'wednesday': '14:00-22:00',
        'thursday': '14:00-22:00',
        'friday': '14:00-23:00',
        'saturday': '10:00-23:00',
        'sunday': '10:00-22:00',
      },
      isHalal: true,
      hasWifi: true,
      acceptsCards: true,
      priceRange: '€€€',
      latitude: 33.6073,
      longitude: -7.5693,
    ),
  ];

  // Mock Deals
  static List<Deal> get deals => [
    Deal(
      id: '1',
      venueId: '1',
      title: 'Afternoon Coffee Special',
      description: 'Perfect afternoon study spot! Quiet atmosphere, great coffee, free WiFi.',
      discountType: 'percentage',
      discountValue: 35,
      originalPrice: 65,
      discountedPrice: 42,
      validFrom: DateTime.now().subtract(const Duration(hours: 2)),
      validUntil: DateTime.now().add(const Duration(hours: 2)),
      maxCapacity: 20,
      currentBookings: 7,
      isActive: true,
      categories: ['coffee', 'study', 'wifi'],
      daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      timeSlots: ['14:00-16:00'],
    ),
    
    Deal(
      id: '2',
      venueId: '2',
      title: 'Traditional Lunch Experience',
      description: 'Authentic Moroccan tagine and couscous during lunch hours',
      discountType: 'percentage',
      discountValue: 25,
      originalPrice: 120,
      discountedPrice: 90,
      validFrom: DateTime.now().subtract(const Duration(hours: 1)),
      validUntil: DateTime.now().add(const Duration(hours: 3)),
      maxCapacity: 15,
      currentBookings: 8,
      isActive: true,
      categories: ['traditional', 'lunch', 'tagine'],
      daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      timeSlots: ['14:00-16:00'],
    ),
    
    Deal(
      id: '3',
      venueId: '3',
      title: 'Weekday Escape Challenge',
      description: 'Team building escape room experience during off-peak hours',
      discountType: 'percentage',
      discountValue: 40,
      originalPrice: 480,
      discountedPrice: 288,
      validFrom: DateTime.now().subtract(const Duration(minutes: 30)),
      validUntil: DateTime.now().add(const Duration(hours: 4)),
      maxCapacity: 6,
      currentBookings: 2,
      isActive: true,
      categories: ['team', 'challenge', 'group'],
      daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday'],
      timeSlots: ['14:00-17:00'],
    ),
    
    Deal(
      id: '4',
      venueId: '4',
      title: 'Relaxing Hammam Session',
      description: 'Traditional Moroccan hammam experience with essential oils',
      discountType: 'percentage',
      discountValue: 30,
      originalPrice: 150,
      discountedPrice: 105,
      validFrom: DateTime.now().subtract(const Duration(hours: 1)),
      validUntil: DateTime.now().add(const Duration(hours: 5)),
      maxCapacity: 8,
      currentBookings: 3,
      isActive: true,
      categories: ['relaxation', 'traditional', 'wellness'],
      daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      timeSlots: ['14:00-17:00'],
    ),
    
    Deal(
      id: '5',
      venueId: '5',
      title: 'Weekday Racing Special',
      description: 'Professional go-kart racing with timing system',
      discountType: 'percentage',
      discountValue: 45,
      originalPrice: 200,
      discountedPrice: 110,
      validFrom: DateTime.now(),
      validUntil: DateTime.now().add(const Duration(hours: 6)),
      maxCapacity: 12,
      currentBookings: 4,
      isActive: true,
      categories: ['racing', 'adrenaline', 'competition'],
      daysOfWeek: ['monday', 'tuesday', 'wednesday', 'thursday'],
      timeSlots: ['14:00-18:00'],
    ),
  ];

  // Mock Users
  // ADDON System Demo Users - Progressive Enhancement Examples
  static List<DeadHourUser> get users => [
    DeadHourUser(
      id: '1',
      name: 'Ahmed Benali - Multi-ADDON Success',
      email: 'ahmed.benali@email.com',
      phone: '+212 661 234 567',
      activeAddons: {UserAddon.BUSINESS, UserAddon.GUIDE, UserAddon.PREMIUM}, // €65/month revenue
      city: 'Casablanca',
      profileImageUrl: 'https://picsum.photos/150/150?random=21',
      joinDate: DateTime.now().subtract(const Duration(days: 120)),
      preferredLanguage: 'ar',
      isVerified: true,
      addonCapabilities: {
        UserAddon.BUSINESS: {'venueId': '1', 'monthlyRevenue': 850},
        UserAddon.GUIDE: {'expertiseAreas': ['Food', 'Culture'], 'rating': 4.8},
        UserAddon.PREMIUM: {'enhancedAnalytics': true, 'prioritySupport': true}
      },
      crossAddonMetrics: {'businessGuideAmplification': 1.4, 'totalEarnings': 65},
      networkEffectMultiplier: 1.4,
      favoriteCategories: ['food', 'entertainment'],
      languages: ['ar', 'fr'],
    ),
    
    DeadHourUser(
      id: '2',
      name: 'Sarah Johnson - Guide ADDON Success',
      email: 'sarah.johnson@email.com',
      phone: '+33 6 12 34 56 78',
      activeAddons: {UserAddon.GUIDE, UserAddon.PREMIUM}, // €35/month revenue
      city: 'Marrakech',
      profileImageUrl: 'https://picsum.photos/150/150?random=22',
      joinDate: DateTime.now().subtract(const Duration(days: 3)),
      preferredLanguage: 'en',
      isVerified: true,
      addonCapabilities: {
        UserAddon.GUIDE: {'expertiseAreas': ['Tourism', 'Culture'], 'rating': 4.9, 'languages': ['en', 'fr']},
        UserAddon.PREMIUM: {'enhancedDiscovery': true, 'priorityBookings': true}
      },
      crossAddonMetrics: {'guideExpertise': 4.9, 'totalEarnings': 35},
      networkEffectMultiplier: 1.2,
      favoriteCategories: ['tourism', 'food', 'wellness'],
      languages: ['en', 'fr'],
    ),
    
    DeadHourUser(
      id: '3',
      name: 'Omar El Fassi - Business ADDON Owner',
      email: 'omar.elfassi@email.com',
      phone: '+212 662 345 678',
      activeAddons: {UserAddon.BUSINESS}, // €30/month revenue
      city: 'Rabat',
      profileImageUrl: 'https://picsum.photos/150/150?random=23',
      joinDate: DateTime.now().subtract(const Duration(days: 89)),
      preferredLanguage: 'ar',
      isVerified: true,
      addonCapabilities: {
        UserAddon.BUSINESS: {'venueId': '4', 'monthlyRevenue': 720, 'category': 'wellness'}
      },
      crossAddonMetrics: {'businessOptimization': 1.3, 'totalEarnings': 30},
      networkEffectMultiplier: 1.1,
      favoriteCategories: ['sports', 'entertainment', 'wellness'],
      languages: ['ar', 'fr'],
    ),
    
    DeadHourUser(
      id: '4',
      name: 'Fatima Alaoui - Consumer (Future ADDON Potential)',
      email: 'fatima.alaoui@email.com',
      phone: '+212 663 456 789',
      activeAddons: {}, // Consumer, ready for ADDON progression
      city: 'Casablanca',
      profileImageUrl: 'https://picsum.photos/150/150?random=24',
      joinDate: DateTime.now().subtract(const Duration(days: 15)),
      preferredLanguage: 'ar',
      isVerified: false,
      addonCapabilities: {},
      crossAddonMetrics: {'discoverScore': 3.8},
      networkEffectMultiplier: 1.0,
      favoriteCategories: ['food', 'wellness'],
      languages: ['ar'],
    ),
  ];

  // Mock Rooms
  static List<Room> get rooms => [
    Room(
      id: '1',
      name: '#coffee-afternoon-deals-casa',
      displayName: 'Coffee Afternoon Deals Casa',
      category: 'food',
      city: 'Casablanca',
      description: 'Share weekend spa deals and wellness experiences in Casa',
      memberCount: 156,
      onlineCount: 23,
      isPublic: true,
      allowDeals: true,
      isPrayerTimeAware: true,
      isHalalOnly: true,
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      lastActivity: DateTime.now().subtract(const Duration(minutes: 2)),
      moderators: ['1', '3'],
      recentMessages: [
        {
          'id': 'm1',
          'userId': 'bot',
          'userName': 'DeadHour Bot',
          'message': '🚨 FLASH DEAL! Café Atlas Maarif: 50% OFF ⏰ Next 2 hours only',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 2)),
          'type': 'deal_alert',
        },
        {
          'id': 'm2',
          'userId': '1',
          'userName': 'Ahmed_Casa',
          'message': 'Perfect timing! I was just looking for a good coffee spot near Twin Center 👍',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 1)),
          'type': 'message',
        },
        {
          'id': 'm3',
          'userId': '2',
          'userName': 'Sara_Local',
          'message': '@Ahmed_Casa Atlas has amazing pastries too! Try the chebakia 🥮',
          'timestamp': DateTime.now().subtract(const Duration(seconds: 30)),
          'type': 'message',
        },
      ],
    ),
    
    Room(
      id: '2',
      name: '#escape-rooms-weekend',
      displayName: 'Escape Rooms Weekend',
      category: 'entertainment',
      city: 'Casablanca',
      description: 'Plan weekend escape room adventures and form teams',
      memberCount: 89,
      onlineCount: 12,
      isPublic: true,
      allowDeals: true,
      isPrayerTimeAware: true,
      isHalalOnly: false,
      createdAt: DateTime.now().subtract(const Duration(days: 32)),
      lastActivity: DateTime.now().subtract(const Duration(minutes: 5)),
      moderators: ['3'],
      recentMessages: [
        {
          'id': 'm4',
          'userId': '3',
          'userName': 'Omar_Casa',
          'message': 'Saturday team formation for Morocco Mall! Who\'s in? 🎮',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 5)),
          'type': 'message',
        },
        {
          'id': 'm5',
          'userId': '2',
          'userName': 'Sarah_Tourist_FR',
          'message': 'I\'d love to join! Is it beginner-friendly? 🇫🇷',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 3)),
          'type': 'message',
        },
      ],
    ),
    
    Room(
      id: '3',
      name: '#cultural-experiences-marrakech',
      displayName: 'Cultural Experiences Marrakech',
      category: 'tourism',
      city: 'Marrakech',
      description: 'Authentic Marrakech experiences with local guides',
      memberCount: 234,
      onlineCount: 45,
      isPublic: false,
      allowDeals: true,
      isPrayerTimeAware: true,
      isHalalOnly: true,
      createdAt: DateTime.now().subtract(const Duration(days: 67)),
      lastActivity: DateTime.now().subtract(const Duration(minutes: 1)),
      moderators: ['3'],
      isPremiumOnly: true,
      recentMessages: [
        {
          'id': 'm6',
          'userId': '3',
          'userName': 'Local_Expert_Youssef',
          'message': 'Hassan II Mosque tour available now! 2 hours • 15€ • English/French 🕌',
          'timestamp': DateTime.now().subtract(const Duration(minutes: 1)),
          'type': 'experience_offer',
        },
      ],
    ),
  ];

  // Mock Business Analytics Data
  static Map<String, dynamic> get businessAnalytics => {
    'todayPerformance': {
      'revenueIncrease': 23,
      'deadHourBookings': 12,
      'platformEarnings': 234,
    },
    'weeklyTraffic': [
      {'day': 'Mon', 'occupancy': 45},
      {'day': 'Tue', 'occupancy': 38},
      {'day': 'Wed', 'occupancy': 42},
      {'day': 'Thu', 'occupancy': 35},
      {'day': 'Fri', 'occupancy': 67},
      {'day': 'Sat', 'occupancy': 89},
      {'day': 'Sun', 'occupancy': 72},
    ],
    'deadHours': [
      {'time': '14:00-16:00', 'occupancy': 35, 'status': 'dead'},
      {'time': '20:00-22:00', 'occupancy': 28, 'status': 'dead'},
    ],
    'monthlyRevenue': {
      'total': 4890,
      'commission': 391,
      'netEarnings': 4499,
      'growth': 34,
    },
  };

  // Mock Community Health Data
  static Map<String, dynamic> get communityHealth => {
    'overallHealth': 'excellent',
    'totalActiveRooms': 47,
    'dailyActiveUsers': 1234,
    'crossRoomInteractions': 67,
    'averageSessionTime': 12,
    'engagementMetrics': {
      'messagesPerUser': 8.4,
      'dealShares': 12.6,
      'successfulMeetups': 89,
      'userSatisfaction': 4.7,
    },
  };

  // Current User (Mock)
  static DeadHourUser get currentUser => users.first;

  // Business Data for logged-in business user
  static Map<String, dynamic> get businessData => {
    'venue': venues.first,
    'activeDeals': deals.where((deal) => deal.isActive).toList(),
    'analytics': businessAnalytics,
    'monthlyStats': {
      'totalBookings': 47,
      'platformRevenue': 1240,
      'newCustomers': 23,
      'averageRating': 4.6,
    },
  };
}

