import '../models/venue.dart';


/// Mock venue data for Morocco-based establishments
class VenueData {
  static List<Venue> get venues => [
        Venue(
          id: '1',
          name: 'Café Central Gueliz',
          category: 'food',
          type: 'Mediterranean Café',
          address: '123 Rue Mohammed V, Gueliz, Casablanca',
          city: 'Casablanca',
          rating: 4.6,
          reviewCount: 234,
          imageUrl: 'https://picsum.photos/400/300?random=11',
          description:
              'Authentic Mediterranean café with traditional Moroccan atmosphere',
          phone: '+212 522 123 456',
          operatingHours: {
            'monday': '08:00-23:00',
            'tuesday': '08:00-23:00',
            'wednesday': '08:00-23:00',
            'thursday': '08:00-23:00',
            'friday': '08:00-23:00',
            'saturday': '09:00-24:00',
            'sunday': '09:00-22:00',
          },
          isHalal: true,
          hasWifi: true,
          acceptsCards: true,
          priceRange: '€€',
          latitude: 33.5731,
          longitude: -7.5898,
        ),
        Venue(
          id: '2',
          name: 'Restaurant Al Fassia',
          category: 'food',
          type: 'Traditional Moroccan',
          address: '232 Avenue Mohammed V, Gueliz, Marrakech',
          city: 'Marrakech',
          rating: 4.8,
          reviewCount: 456,
          imageUrl: 'https://picsum.photos/400/300?random=12',
          description: 'Authentic Moroccan cuisine in traditional setting',
          phone: '+212 524 234 567',
          operatingHours: {
            'monday': '12:00-22:00',
            'tuesday': '12:00-22:00',
            'wednesday': '12:00-22:00',
            'thursday': '12:00-22:00',
            'friday': '12:00-23:00',
            'saturday': '12:00-23:00',
            'sunday': '12:00-22:00',
          },
          isHalal: true,
          hasWifi: false,
          acceptsCards: true,
          priceRange: '€€€',
          latitude: 31.6295,
          longitude: -7.9811,
        ),
        Venue(
          id: '3',
          name: 'Escape Hunt Morocco Mall',
          category: 'entertainment',
          type: 'Escape Room',
          address: 'Morocco Mall, Casablanca',
          city: 'Casablanca',
          rating: 4.5,
          reviewCount: 189,
          imageUrl: 'https://picsum.photos/400/300?random=13',
          description: 'Thrilling escape room experiences for groups',
          phone: '+212 522 345 678',
          operatingHours: {
            'monday': '10:00-22:00',
            'tuesday': '10:00-22:00',
            'wednesday': '10:00-22:00',
            'thursday': '10:00-22:00',
            'friday': '10:00-23:00',
            'saturday': '10:00-23:00',
            'sunday': '10:00-22:00',
          },
          isHalal: true,
          hasWifi: true,
          acceptsCards: true,
          priceRange: '€€',
          latitude: 33.5731,
          longitude: -7.6298,
        ),
        Venue(
          id: '4',
          name: 'Hammam de la Rose',
          category: 'wellness',
          type: 'Traditional Hammam',
          address: '45 Rue de la Liberté, Rabat',
          city: 'Rabat',
          rating: 4.7,
          reviewCount: 123,
          imageUrl: 'https://picsum.photos/400/300?random=14',
          description: 'Traditional Moroccan hammam experience',
          phone: '+212 537 456 789',
          operatingHours: {
            'monday': '09:00-20:00',
            'tuesday': '09:00-20:00',
            'wednesday': '09:00-20:00',
            'thursday': '09:00-20:00',
            'friday': '14:00-20:00',
            'saturday': '09:00-21:00',
            'sunday': '09:00-20:00',
          },
          isHalal: true,
          hasWifi: false,
          acceptsCards: false,
          priceRange: '€€',
          latitude: 34.0209,
          longitude: -6.8416,
        ),
        Venue(
          id: '5',
          name: 'Karting Club Casa',
          category: 'entertainment',
          type: 'Go-Kart Racing',
          address: 'Zone Industrielle Sidi Bernoussi, Casablanca',
          city: 'Casablanca',
          rating: 4.4,
          reviewCount: 267,
          imageUrl: 'https://picsum.photos/400/300?random=15',
          description: 'Professional go-kart racing track',
          phone: '+212 522 567 890',
          operatingHours: {
            'monday': '14:00-22:00',
            'tuesday': '14:00-22:00',
            'wednesday': '14:00-22:00',
            'thursday': '14:00-22:00',
            'friday': '14:00-23:00',
            'saturday': '10:00-23:00',
            'sunday': '10:00-22:00',
          },
          isHalal: true,
          hasWifi: true,
          acceptsCards: true,
          priceRange: '€€€',
          latitude: 33.6073,
          longitude: -7.5693,
        ),
      ];
}